import type { FilamentProfile, PrintSettings, PrinterProfile } from '../types';
import { lineWidthFor } from '../slicer';

/*
 * Print settings for use in other slicers. Supports are always written as
 * OFF so people can add their own (painted, tree, or normal) in their slicer.
 */

const PRUSA_FILL: Record<PrintSettings['infillPattern'], string> = {
  lines: 'rectilinear',
  grid: 'grid',
  triangles: 'triangles',
};

/** PrusaSlicer / SuperSlicer config (File → Import → Import Config). */
export function toPrusaIni(printer: PrinterProfile, filament: FilamentProfile, s: PrintSettings): string {
  const x0 = printer.originCenter ? -printer.bedX / 2 : 0;
  const y0 = printer.originCenter ? -printer.bedY / 2 : 0;
  const bedShape =
    printer.bedShape === 'circle'
      ? Array.from({ length: 64 }, (_, i) => {
          const a = (i / 64) * Math.PI * 2;
          const r = printer.bedX / 2;
          return `${(Math.cos(a) * r).toFixed(2)}x${(Math.sin(a) * r).toFixed(2)}`;
        }).join(',')
      : `${x0}x${y0},${x0 + printer.bedX}x${y0},${x0 + printer.bedX}x${y0 + printer.bedY},${x0}x${y0 + printer.bedY}`;
  const oneLine = (g: string) => g.replace(/\r?\n/g, '\\n');
  const speed = (v: number) => Math.min(v, printer.maxPrintSpeed, filament.maxSpeed);
  const lines: [string, string | number][] = [
    ['# generated by', '3D Splicer'],
    ['printer_notes', `${printer.manufacturer} ${printer.name}`],
    ['bed_shape', bedShape],
    ['max_print_height', printer.maxZ],
    ['nozzle_diameter', s.nozzleDiameter],
    ['filament_diameter', printer.filamentDiameter],
    ['gcode_flavor', printer.flavor === 'klipper' ? 'klipper' : printer.flavor === 'reprap' ? 'reprapfirmware' : 'marlin2'],
    ['retract_length', +(printer.retractLength * filament.retractFactor).toFixed(2)],
    ['retract_speed', printer.retractSpeed],
    ['retract_lift', s.zHop],
    ['start_gcode', oneLine(convertPlaceholders(printer.startGcode, printer))],
    ['end_gcode', oneLine(convertPlaceholders(printer.endGcode, printer))],
    ['layer_height', s.layerHeight],
    ['first_layer_height', s.firstLayerHeight],
    ['extrusion_width', lineWidthFor(s)],
    ['perimeters', s.wallCount],
    ['top_solid_layers', s.topLayers],
    ['bottom_solid_layers', s.bottomLayers],
    ['fill_density', `${s.infillDensity}%`],
    ['fill_pattern', PRUSA_FILL[s.infillPattern]],
    ['perimeter_speed', speed(s.printSpeed)],
    ['external_perimeter_speed', speed(s.outerWallSpeed)],
    ['infill_speed', speed(s.printSpeed)],
    ['solid_infill_speed', speed(s.printSpeed)],
    ['first_layer_speed', s.firstLayerSpeed],
    ['travel_speed', s.travelSpeed],
    ['seam_position', s.seam ?? 'aligned'],
    ['ironing', s.ironing ? 1 : 0],
    ['ironing_type', 'topmost'],
    ['ironing_flowrate', `${s.ironingFlow}%`],
    ['ironing_speed', s.ironingSpeed],
    ['ironing_spacing', s.ironingSpacing],
    ['support_material', 0],
    ['support_material_auto', 0],
    ['skirts', s.adhesion === 'skirt' ? s.skirtLoops : 0],
    ['skirt_distance', s.skirtDistance],
    ['brim_width', s.adhesion === 'brim' ? s.brimWidth : 0],
    ['temperature', filament.nozzleTemp],
    ['first_layer_temperature', filament.firstLayerNozzleTemp],
    ['bed_temperature', printer.heatedBed ? filament.bedTemp : 0],
    ['first_layer_bed_temperature', printer.heatedBed ? filament.bedTemp : 0],
    ['max_fan_speed', filament.fanSpeed],
    ['min_fan_speed', filament.fanSpeed],
    ['cooling', filament.fanSpeed > 0 ? 1 : 0],
    ['extrusion_multiplier', filament.flow],
    ['filament_density', filament.density],
    ['filament_cost', filament.costPerKg],
    ['filament_type', filament.material === 'Composite' || filament.material === 'Other' ? 'PLA' : filament.material.toUpperCase()],
  ];
  return lines.map(([k, v]) => (k.startsWith('#') ? `${k} ${v}` : `${k} = ${v}`)).join('\n') + '\n';
}

/** PrusaSlicer uses [placeholders]; ours use {placeholders}. */
function convertPlaceholders(g: string, printer: PrinterProfile): string {
  return g
    .replace(/\{first_layer_nozzle_temp\}/g, '[first_layer_temperature]')
    .replace(/\{nozzle_temp\}/g, '[temperature]')
    .replace(/\{first_layer_bed_temp\}/g, '[first_layer_bed_temperature]')
    .replace(/\{bed_temp\}/g, '[bed_temperature]')
    .replace(/\{max_z\}/g, '[max_print_height]')
    .replace(/\{filament_diameter\}/g, '[filament_diameter]')
    .replace(/\{bed_x\}/g, String(printer.bedX))
    .replace(/\{bed_y\}/g, String(printer.bedY));
}

/** Plain-English settings sheet for copying into any slicer by hand. */
export function toSettingsText(printer: PrinterProfile, filament: FilamentProfile, s: PrintSettings): string {
  const rows: [string, string][] = [
    ['Printer', `${printer.manufacturer} ${printer.name}`],
    ['Build volume', `${printer.bedX} x ${printer.bedY} x ${printer.maxZ} mm${printer.bedShape === 'circle' ? ' (round bed)' : ''}`],
    ['Nozzle', `${s.nozzleDiameter} mm`],
    ['Filament', `${filament.name} (${printer.filamentDiameter} mm)`],
    ['Nozzle temperature', `${filament.nozzleTemp} °C (first layer ${filament.firstLayerNozzleTemp} °C)`],
    ['Bed temperature', printer.heatedBed ? `${filament.bedTemp} °C` : 'no heated bed'],
    ['Cooling fan', `${filament.fanSpeed} %`],
    ['Flow', `${Math.round(filament.flow * 100)} %`],
    ['Layer height', `${s.layerHeight} mm (first layer ${s.firstLayerHeight} mm)`],
    ['Walls / perimeters', String(s.wallCount)],
    ['Top / bottom layers', `${s.topLayers} / ${s.bottomLayers}`],
    ['Infill', `${s.infillDensity} % ${s.infillPattern}`],
    ['Print speed', `${s.printSpeed} mm/s (outer wall ${s.outerWallSpeed}, first layer ${s.firstLayerSpeed})`],
    ['Travel speed', `${s.travelSpeed} mm/s`],
    ['Retraction', s.retraction ? `${+(printer.retractLength * filament.retractFactor).toFixed(2)} mm at ${printer.retractSpeed} mm/s` : 'off'],
    ['Z-hop', s.zHop ? `${s.zHop} mm` : 'off'],
    ['Bed adhesion', s.adhesion === 'brim' ? `brim ${s.brimWidth} mm` : s.adhesion === 'skirt' ? `skirt, ${s.skirtLoops} loops` : 'none'],
    ['Variable layer height', s.adaptiveLayers ? `adaptive, quality ${s.adaptiveQuality} %` : 'off'],
    ...(s.layerRanges ?? []).map((r, i): [string, string] => [`Height range ${i + 1}`, `${r.from}–${r.to} mm at ${r.height} mm layers`]),
    ['Seam', s.seam ?? 'aligned'],
    ['Ironing', s.ironing ? `top surfaces, ${s.ironingFlow} % flow, ${s.ironingSpeed} mm/s, ${s.ironingSpacing} mm spacing` : 'off'],
    ['Supports', 'OFF: add your own in your slicer'],
  ];
  const w = Math.max(...rows.map(([k]) => k.length));
  return (
    '3D Splicer print settings\n=========================\n\n' +
    rows.map(([k, v]) => `${k.padEnd(w)}  ${v}`).join('\n') +
    '\n'
  );
}

export const HOW_TO_OPEN = `How to open this project
========================

Files
-----
Plate 1.3mf, Plate 2.3mf, ...  One file per plate. Pieces are already laid flat and placed.
All plates.3mf                 Every piece in one file. They open together on plate 1
                               (overlapping); press Arrange to spread them over the plates.
Creality-Orca project (beta).3mf
                               EXPERIMENTAL: plates already set up for Creality Print,
                               OrcaSlicer and Bambu Studio. Use File > Open Project.
Original model.3mf             The whole model before cutting, for reference.
settings.ini                   Print settings for PrusaSlicer / SuperSlicer.
SETTINGS.txt                   The same settings in plain English, for any slicer.

Supports are turned OFF in these settings so you can add your own.

Creality Print, OrcaSlicer, Bambu Studio (and Elegoo / Anycubic slicers based on them)
-------------------------------------------------------------------------------------
Easiest, works every time:
1. Choose your printer and filament first.
2. Open "All plates.3mf". All pieces appear on plate 1, on top of each other.
3. Press Arrange (the Arrange button, or the A key). The slicer spreads the pieces out
   and adds as many plates as it needs. If it asks, allow it to add plates. If it
   doesn't, add plates with the + button next to the plates and press Arrange again.
4. Copy any values you want from SETTINGS.txt.
5. Supports: turn on "Enable support" and pick Normal or Tree, or use the support
   painting tool to paint exactly where supports go.

Or try the beta file with the plates already set up:
1. File > Open Project and choose "Creality-Orca project (beta).3mf".
2. If the slicer asks whether to load the project's settings, choose Yes to get the plates.
   Then pick your own printer and filament presets again (the file brings simple
   "3D Splicer" presets with it).
3. If the pieces still all land on plate 1 or you see an error, use "All plates.3mf" above.

Or open one "Plate N.3mf" at a time: these always work in every slicer.

PrusaSlicer / SuperSlicer
-------------------------
1. File > Import > Import Config... and choose settings.ini.
2. File > Import > Import STL/3MF/STEP/OBJ... and choose "Plate 1.3mf".
3. Supports: Print Settings > Support material, or right-click a piece > Paint-on supports.

Ultimaker Cura
--------------
1. Open "Plate 1.3mf" (one plate at a time: Cura has one build plate).
2. Select your printer and copy the values from SETTINGS.txt.
3. Supports: tick "Generate Support" (choose Normal or Tree), or use the Support Blocker tool.

Other slicers
-------------
Open each "Plate N.3mf" (or import it as a model), choose your printer, copy the values from
SETTINGS.txt, and turn on or paint supports where needed.

Dowel joints: each pin on one piece fits the matching hole in the neighbouring piece.
`;
