import type { FilamentProfile, Layer, PathKind, PrintSettings, PrinterProfile, PrintStats } from '../types';

export interface GcodeOptions {
  printer: PrinterProfile;
  filament: FilamentProfile;
  settings: PrintSettings;
  lineWidth: number;
  modelName?: string;
}

const RETRACT_MIN_TRAVEL = 1.5; // mm

export function fillTemplate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}

/** Cross-section of an extruded line (rectangle with rounded ends), in mm². */
export function extrusionArea(width: number, height: number): number {
  return (width - height) * height + Math.PI * (height / 2) ** 2;
}

/** Time for a move of length d at speed v with acceleration a (trapezoid profile). */
function moveTime(d: number, v: number, a: number): number {
  if (d <= 0) return 0;
  const accelDist = (v * v) / a;
  return d >= accelDist ? d / v + v / a : 2 * Math.sqrt(d / a);
}

const f3 = (n: number) => n.toFixed(3);
const f2 = (n: number) => n.toFixed(2);
const f5 = (n: number) => n.toFixed(5);

const KIND_LABEL: Record<PathKind, string> = {
  'outer-wall': 'WALL-OUTER',
  'inner-wall': 'WALL-INNER',
  'solid-infill': 'SKIN',
  'sparse-infill': 'FILL',
  support: 'SUPPORT',
  skirt: 'SKIRT',
};

export function generateGcode(layers: Layer[], opts: GcodeOptions): { gcode: string; stats: PrintStats } {
  const { printer, filament, settings: s, lineWidth: lw } = opts;
  const filamentArea = Math.PI * (printer.filamentDiameter / 2) ** 2;
  const accel = printer.acceleration || 1000;
  const retract = s.retraction ? printer.retractLength * filament.retractFactor : 0;
  const retractF = printer.retractSpeed * 60;
  const speedCap = Math.min(printer.maxPrintSpeed, filament.maxSpeed);
  const cap = (v: number) => Math.max(1, Math.min(v, speedCap));
  const fanValue = Math.round((filament.fanSpeed / 100) * 255);

  const out: string[] = [];
  let e = 0; // absolute E within the current layer (reset with G92 each layer)
  let totalE = 0;
  let time = 0;
  let x = 0, y = 0, z = 0;
  let retracted = false;

  const values = {
    nozzle_temp: filament.nozzleTemp,
    first_layer_nozzle_temp: filament.firstLayerNozzleTemp,
    bed_temp: printer.heatedBed ? filament.bedTemp : 0,
    first_layer_bed_temp: printer.heatedBed ? filament.bedTemp : 0,
    bed_x: printer.bedX,
    bed_y: printer.bedY,
    max_z: printer.maxZ,
    filament_diameter: printer.filamentDiameter,
    layer_height: s.layerHeight,
  };

  out.push(
    '; Generated by 3D Splicer - https://github.com/kellieja/3d-splicer',
    `; model: ${opts.modelName ?? 'model'}`,
    `; printer: ${printer.manufacturer} ${printer.name}`,
    `; filament: ${filament.name} (${printer.filamentDiameter} mm)`,
    `; nozzle: ${s.nozzleDiameter} mm, line width: ${f2(lw)} mm`,
    `; layer height: ${s.layerHeight} mm, first layer: ${s.firstLayerHeight} mm`,
    `; walls: ${s.wallCount}, top/bottom: ${s.topLayers}/${s.bottomLayers}, infill: ${s.infillDensity}% ${s.infillPattern}`,
    `; supports: ${s.supports ? `yes (${s.supportAngle}°)` : 'no'}, adhesion: ${s.adhesion}`,
    `;LAYER_COUNT:${layers.length}`,
    '; ---- start G-code ----',
    fillTemplate(printer.startGcode, values),
    '; ---- end of start G-code ----',
    'G90',
    'M82 ; absolute extrusion',
    'G92 E0',
    'M107 ; fan off for the first layer',
  );

  const doRetract = () => {
    if (retract <= 0 || retracted) return;
    e -= retract;
    out.push(`G1 E${f5(e)} F${retractF}`);
    time += retract / printer.retractSpeed;
    retracted = true;
  };
  const doUnretract = () => {
    if (!retracted) return;
    e += retract;
    out.push(`G1 E${f5(e)} F${retractF}`);
    time += retract / printer.retractSpeed;
    retracted = false;
  };
  const travel = (tx: number, ty: number) => {
    const d = Math.hypot(tx - x, ty - y);
    if (d < 0.001) return;
    const long = d > RETRACT_MIN_TRAVEL;
    if (long) doRetract();
    if (long && s.zHop > 0) out.push(`G1 Z${f3(z + s.zHop)} F${Math.min(s.travelSpeed, 20) * 60}`);
    out.push(`G0 X${f3(tx)} Y${f3(ty)} F${Math.round(s.travelSpeed * 60)}`);
    if (long && s.zHop > 0) out.push(`G1 Z${f3(z)} F${Math.min(s.travelSpeed, 20) * 60}`);
    time += moveTime(d, s.travelSpeed, accel);
    x = tx;
    y = ty;
  };

  for (const layer of layers) {
    const first = layer.index === 0;
    const h = layer.height;
    const ePerMm = (extrusionArea(lw, h) / filamentArea) * filament.flow;

    out.push(`;LAYER:${layer.index}`, `; z = ${f3(layer.z)}`);
    doRetract();
    z = layer.z;
    out.push(`G1 Z${f3(z)} F600`);
    out.push(`G92 E${f5(retracted ? -retract : 0)}`);
    e = retracted ? -retract : 0;

    if (layer.index === 1) {
      if (filament.firstLayerNozzleTemp !== filament.nozzleTemp) out.push(`M104 S${filament.nozzleTemp}`);
      if (fanValue > 0) out.push(`M106 S${Math.round(fanValue / 2)}`);
    } else if (layer.index === 2 && fanValue > 0) {
      out.push(`M106 S${fanValue}`);
    }

    let lastKind: PathKind | null = null;
    for (const path of layer.paths) {
      const pts = path.points;
      if (pts.length < 4) continue;
      if (path.kind !== lastKind) {
        out.push(`;TYPE:${KIND_LABEL[path.kind]}`);
        lastKind = path.kind;
      }
      const speed = cap(
        first ? s.firstLayerSpeed : path.kind === 'outer-wall' ? s.outerWallSpeed : s.printSpeed,
      );
      const feed = Math.round(speed * 60);

      travel(pts[0], pts[1]);
      doUnretract();

      const count = pts.length / 2 + (path.closed ? 1 : 0);
      let wroteFeed = false;
      for (let k = 1; k < count; k++) {
        const idx = (k % (pts.length / 2)) * 2;
        const nx = pts[idx], ny = pts[idx + 1];
        const d = Math.hypot(nx - x, ny - y);
        if (d < 0.01) continue;
        const de = d * ePerMm;
        e += de;
        totalE += de;
        out.push(`G1 X${f3(nx)} Y${f3(ny)} E${f5(e)}${wroteFeed ? '' : ` F${feed}`}`);
        wroteFeed = true;
        time += moveTime(d, speed, accel);
        x = nx;
        y = ny;
      }
    }
    // Layer change / Z move time.
    time += 0.5;
  }

  doRetract();
  out.push('; ---- end G-code ----', fillTemplate(printer.endGcode, values), '');

  const lengthMm = totalE;
  const volumeCm3 = (lengthMm * filamentArea) / 1000;
  const weight = volumeCm3 * filament.density;
  // Heat-up is roughly 2–4 minutes on most printers.
  time += 180;

  const stats: PrintStats = {
    layerCount: layers.length,
    estimatedTime: time,
    filamentLength: lengthMm / 1000,
    filamentWeight: weight,
    cost: (weight / 1000) * filament.costPerKg,
    height: layers.length ? layers[layers.length - 1].z : 0,
  };

  out.splice(
    1,
    0,
    `; estimated print time: ${formatDuration(stats.estimatedTime)}`,
    `; filament used: ${f2(stats.filamentLength)} m, ${f2(stats.filamentWeight)} g`,
  );

  return { gcode: out.join('\n'), stats };
}

export function formatDuration(seconds: number): string {
  const m = Math.round(seconds / 60);
  const h = Math.floor(m / 60);
  const d = Math.floor(h / 24);
  if (d > 0) return `${d}d ${h % 24}h ${m % 60}m`;
  if (h > 0) return `${h}h ${m % 60}m`;
  return `${m}m`;
}
